---@class HelperData
---@field construct AxisPosition
---@field camera AxisPosition
---@field screen {width:number, height:number}
---@field tanFov number
---@field aspectRatio number
---@field template string
